"""Add sent_message_id and sent_at to scheduled_responses

Revision ID: d8a7e58b8dc2
Revises: 1072e9bf7d5d
Create Date: 2026-04-15 22:00:26.655835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a7e58b8dc2'
down_revision: Union[str, Sequence[str], None] = '1072e9bf7d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_diaries_user_date'), table_name='diaries')
    op.drop_index(op.f('idx_messages_conversation_sent'), table_name='messages')
    op.add_column('scheduled_responses', sa.Column('sent_message_id', sa.Integer(), nullable=True))
    op.add_column('scheduled_responses', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_scheduled_responses_pending'), table_name='scheduled_responses', postgresql_where="(status = 'PENDING'::responsestatus)")
    op.create_foreign_key(None, 'scheduled_responses', 'messages', ['sent_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_responses', type_='foreignkey')
    op.create_index(op.f('idx_scheduled_responses_pending'), 'scheduled_responses', ['status', 'scheduled_at'], unique=False, postgresql_where="(status = 'PENDING'::responsestatus)")
    op.drop_column('scheduled_responses', 'sent_at')
    op.drop_column('scheduled_responses', 'sent_message_id')
    op.create_index(op.f('idx_messages_conversation_sent'), 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.create_index(op.f('idx_diaries_user_date'), 'diaries', ['user_id', 'diary_date'], unique=False)
    # ### end Alembic commands ###
